#import Boilerplate
#import Definitions

#import RayGeneratorDef;
#import RayDef;
#import TriangleDef;

layout(binding = 0) #import RayGeneratorSSBODef;
layout(binding = 1) #import OverlaySSBODef;
layout(binding = 2) readonly #import TriangleSSBODef;
layout(binding = 3) readonly #import TransformedVertexSSBODef;
layout(binding = 4) #import OverlayUniformBufferObjectDef o_ubo;
layout(binding = 5) #import UniformBufferObjectDef ubo;

#import CreateSimpleRay

vec2 project_vertex(vec3 vertex) {
    vec3 rel = vertex - ubo.position;
    float cx = dot(rel, ubo.u);
    float cy = dot(rel, ubo.v);
    float cz = dot(rel, -ubo.w);
    float r = ubo.width * 0.5;
    float b = ubo.height * 0.5;
    float d = (cos(ubo.fov / 2.0) / sin(ubo.fov / 2.0)) * r;
    float px = (cx / cz) * d;
    float py = (cy / cz) * d;
    float sx = ((px + r) / (2.0 * r)) * ubo.width;
    float sy = ((b - py) / (2.0 * b)) * ubo.height;
    return vec2(sx - 0.5, sy - 0.5);
}

void main() {
    if (gl_GlobalInvocationID.x == 0 && o_ubo.single_selected_vid != -1)
        selected_vertex_position = project_vertex(vertexIn[o_ubo.single_selected_vid].xyz);
	int rx = int(gl_GlobalInvocationID.x%int(o_ubo.image_width));
    int ry = int(gl_GlobalInvocationID.x/int(o_ubo.image_width));
    if (rx == o_ubo.mouse_x && ry == o_ubo.mouse_y) {
        if (o_ubo.mode == TRIANGLE_SELECT) {
		    hovered_tid = raygenIn[gl_GlobalInvocationID.x].tid;
        } else if (o_ubo.mode == VERTEX_SELECT) {
            hovered_tid = -1;
            Ray ray = create_ray(vec2(rx, ry));
            Triangle tri = triangleIn[raygenIn[gl_GlobalInvocationID.x].tid];
            vec3 _a = vertexIn[tri.a].xyz;
            vec3 _b = vertexIn[tri.b].xyz;
            vec3 _c = vertexIn[tri.c].xyz;
            vec3 e1 = _b - _a;
            vec3 e2 = _c - _a;
            vec3 h = cross(ray.direction, e2);
            float a = dot(e1, h);
            if (abs(a) < EPS) return;
            float f = 1.0 / a;
            vec3 s = ray.position - _a;
            float u = f*dot(s, h);
            if (u < 0.0 || u > 1.0) return;
            vec3 q = cross(s, e1);
            float v = f*dot(ray.direction, q);
            if (v < 0.0 || u + v > 1.0) return;
            float w = 1.0f - u - v;
            hovered_tid = (u > v && u > w) ? tri.b : (v > w ? tri.c : tri.a);
            vertex_position = project_vertex(vertexIn[hovered_tid].xyz);
        }
    }
}
