#version 450

layout(binding = 0) buffer WorkGroupHistorySSBOIn {
    uint wgHist[ ][16];
};

layout(binding = 1) buffer BucketBaseSSBOIn {
    uint bucketIn[16];
};

layout(push_constant) uniform PushConstants {
    uint elements; // workgroups, not number of triangles btw
    uint bitstart;
} pc;

layout (local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

void main() {
    uint bucket = gl_GlobalInvocationID.x;
    if (bucket >= 16) return;
    uint total = 0;
    for (uint wg = 0; wg < pc.elements; wg++) {
        total += wgHist[wg][bucket];
    }
    bucketIn[bucket] = total;
}
