#import Boilerplate
#import Definitions

#import BVHNodeDef;
#import RayGeneratorDef;
#import RayDef;
#import TriangleDef;
#import HitDef;

layout(binding = 0) #import UniformBufferObjectDef ubo;
layout(binding = 1) #import RayGeneratorSSBODef;
layout(binding = 2, rgba8) #import OutputImageDef;
layout(binding = 3) readonly #import TriangleSSBODef;
layout(binding = 4) readonly #import TransformedVertexSSBODef;
layout(binding = 5) readonly #import NormalSSBODef;
layout(binding = 6) readonly #import BVHNodeSSBODef;

#import CreateSimpleRay
#import CutViewport
#import TriangleIntersectSuite

vec3 key_light = vec3(0.408248, 0.408248, 0.816497);
vec3 fill_light = vec3(-0.440225, 0.17609, 0.880451);
vec3 back_light = vec3(0, -0.447214, 0.894427);
vec3 background_color = vec3(0.12);

float lambert(vec3 n, vec3 l) {
    return max(dot(n, l), 0.0);
}

vec3 shade(Ray ray, Hit hit) {
    if (ubo.debugmode == DEBUG_NORMALS) return hit.normal;
    float ambient = 0.08;
    float rim = 1.0 - lambert(hit.normal, normalize(ubo.position - hit.position));
    rim = pow(rim, 2.0) * 0.15;
    float lighting = 0.4*lambert(hit.normal, key_light) +
                     0.35*lambert(hit.normal, fill_light) +
                     0.3*lambert(hit.normal, back_light);
    return clamp((lighting + rim + ambient) * vec3(0.8), vec3(0.25), vec3(1));
}

float plane_intersect(Ray ray, vec3 planepoint, vec3 normal) {
    return dot(planepoint - ray.position, normal) / dot(ray.direction, normal);
}

vec3 getcolor(vec2 ray_coordinate, inout uint hit_id, inout float hit_distance) {
	// create ray
    Ray ray = create_ray(ray_coordinate);

    // background color
    vec3 color = background_color;

    // trace
    Hit hit;
    hit.distance = -1.0;
    float grid_plane_distance = plane_intersect(ray, vec3(0, 0, 0), vec3(0, 1.0, 0));
    vec3 grid_plane_point = ray.position + (ray.direction * grid_plane_distance);
    float grid_plane_tolerance = grid_plane_distance / 100.0;
    float grid_x_tolerance = 0.0;
    float grid_y_tolerance = 0.0;
    float xfract = fract(grid_plane_point.x);
    float yfract = fract(grid_plane_point.z);
    hit = trace(ray, hit_id);
    bool gridhit = false;
    float gridmix = 0.0;
    if (ubo.grid != 0 && grid_plane_distance > 0.0 &&
        (hit.distance <= 0.0 || hit.distance > grid_plane_distance) &&
        (xfract < grid_plane_tolerance + grid_x_tolerance ||
        yfract < grid_plane_tolerance + grid_y_tolerance)) {
        float divfract = 2.0 * abs((xfract < yfract ? xfract : yfract) - (grid_plane_tolerance / 2.0));
        divfract = min(divfract, 2.0 * abs((xfract > yfract ? xfract : yfract) - (grid_plane_tolerance / 2.0)));
        float alias = 1.0 - (divfract / grid_plane_tolerance);
        gridmix = alias / grid_plane_distance;
        gridhit = true;
    }
    if (hit.distance > 0.0) {
        color = shade(ray, hit);
        if (ubo.showdof != 0) {
            float distance_to_focal_plane = abs(dot(hit.position - ubo.position, normalize(ubo.look)) - ubo.focus);
            color = mix(color, vec3(1.0), 1.0 / ((ubo.aperature * distance_to_focal_plane) + EPS));
        }
        if (gridhit) {
            color = mix(color, vec3(0.7), gridmix);
        }
    } else if (gridhit) {
        color = mix(background_color, vec3(0.7), gridmix);
    }
    hit_distance = hit.distance;
    if (ubo.debugmode == DEBUG_BVH) {
        float bvhmix = float(bvh_counter) / 100.0;
        color = mix(color, vec3(0, 1, 0), pow(bvhmix, 3.0));
    }
	return color;
}

void main() {
	// create ray generator coordinates
	int rx = int(gl_GlobalInvocationID.x%int(ubo.width));
    int ry = int(gl_GlobalInvocationID.x/int(ubo.width));

	// reject any rays outside of the viewport
    if (cut_viewport(rx, ry)) return;

	// calculate ray color
	vec3 color = vec3(0);
    uint hit_id = -1;
    float hit_distance = -1.0;
	color = getcolor(vec2(rx, ry), hit_id, hit_distance);
    raygenIn[gl_GlobalInvocationID.x].tid = hit_id;
    raygenIn[gl_GlobalInvocationID.x].distance = hit_distance;

    // failures
    if (stack_failure) color = vec3(1.0, 0.0, 0.0);

    // write to image
	imageStore(outputImage, ivec2(rx, ry), vec4(color, 1.0));
}
