#version 450

layout(binding = 0) buffer WorkGroupHistorySSBOIn {
    uint wgHist[ ][16];
};

layout(binding = 1) buffer WorkGroupOffsetSSBOIn {
    uint globalOffset[ ][16];
};

layout(push_constant) uniform PushConstants {
    uint elements; // workgroups, not number of triangles btw
    uint bitstart;
} pc;

layout (local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

void main() {
    uint globalID = gl_GlobalInvocationID.x;
    uint totalEntries = pc.elements * 16u;
    if (globalID >= totalEntries)
        return;
    uint bucket = globalID % 16u;
    uint wgID   = globalID / 16u;
    uint sum = 0;
    for (uint i = 0; i < wgID; i++) {
        sum += wgHist[i][bucket];
    }
    globalOffset[wgID][bucket] = sum;
}
