#import Boilerplate

layout(binding = 0) #import MortonSSBODef;
layout(binding = 1) #import MortonSSBOSwapDef;
layout(binding = 2) #import WorkGroupHistorySSBODef;
layout(push_constant) #import PushConstantDef pc;

shared uint local_history[16];

void main() {
    uint idx = gl_GlobalInvocationID.x;
    uint tid = gl_LocalInvocationID.x;
    uint wgID = gl_WorkGroupID.x;
    if (tid < 16) local_history[tid] = 0;
    barrier();
    if (idx < pc.elements) atomicAdd(local_history[((pc.bitstart%8 != 0 ? mortonSwap[idx] : mortonIn[idx]) >> pc.bitstart) & 0xFu], 1);
    barrier();
    if (tid < 16) wgHist[wgID][tid] = local_history[tid];
}
