#import Boilerplate

layout(binding = 0) #import WorkGroupHistorySSBODef;
layout(binding = 1) #import WorkGroupOffsetSSBODef;
layout(binding = 2) #import BucketBaseSSBODef;
layout(push_constant) #import PushConstantDef pc;

void main() {
    uint globalID = gl_GlobalInvocationID.x;
    uint totalEntries = pc.elements * 16u;
    if (globalID >= totalEntries) return;
    bool bucket_invocation = globalID < 16;
    uint bucket = globalID % 16u;
    uint wgID = globalID / 16u;
    uint sum = 0;
    uint bucketsum = 0;
    for (uint i = 0; i < pc.elements; i++) {
        if (i < wgID) sum += wgHist[i][bucket];
        else if (!bucket_invocation) break;
        if (bucket_invocation) bucketsum += wgHist[i][globalID];
    }
    globalOffset[wgID][bucket] = sum;
    if (bucket_invocation) bucketIn[globalID] = bucketsum;
}
