#version 450

#define MAX_RECURSIVE_DEPTH 2000
#define MAX_BOUNCES 100
#define EPS 0.0001

#define LAMBERTIAN_MODEL 2

struct RayGenerator {
    vec3 normal;
	float time;
    uint tid;
    uint occlusions;
};

struct Ray {
    vec3 position;
    vec3 direction;
};

struct Hit {
    float distance;
    uint material;
    vec3 normal;
    vec3 position;
};

struct Triangle {
    vec3 a;
    vec3 b;
    vec3 c;
    vec3 an;
    vec3 bn;
    vec3 cn;
    uint material;
};

struct Material {
    vec3 emission;
    vec3 ambient;
    vec3 diffuse;
    vec3 specular;
    float rindex;
    float shiny;
    uint model;
};

struct NodeBVH {
    vec3 min;
    vec3 max;
    uint config;
    uint left;
    uint right;
};

layout(binding = 0) uniform UniformBufferObject {
	vec3 look;
	vec3 position;
	vec3 up;
    vec3 u;
    vec3 v;
    vec3 w;
    float fov;
    float width;
    float height;
    uint triangles;
    vec2 viewport;
    uint bvhsize;
	float frametime;
	float frameless;
	uint seed;
	uint shadows;
	uint reflections;
	uint lighting;
    uint trace;
    uint sdf;
    uint sdfsize;
    float sdfsmooth;
    uint maxmarches;
    float time;
    uint antialiasing;
    uint lightssize;
    uint grid;
	uint mouse_x;
	uint mouse_y;
    uint samples;
    uint reset;
} ubo;

layout(binding = 1) buffer RayGeneratorSSBOIn {
   RayGenerator raygenIn[ ];
};

layout(binding = 2, rgba16f) uniform image2D hdrImage;

layout(binding = 3) readonly buffer TriangleSSBOIn {
    Triangle triangleIn[ ];
};

layout(binding = 4) readonly buffer MaterialSSBOIn {
    Material materialIn[ ];
};

layout(binding = 5) readonly buffer BVHSSBOIn {
    NodeBVH bvhIn[ ];
};

layout(binding = 6) buffer OverlaySSBO {
	uint hovered_tid;
};

layout (local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

const float PI = 3.14159265358979323846;
bool stack_failure = false;
float random_seed = 0;

vec3 background_color(Ray ray) {
    return vec3(0.0);
}

float noise(float n) {
	return fract(n*17.0*fract(n*0.3183099));
}

float random() {
    random_seed = (random_seed + 1.23456789) * 0.61803398875;
    return noise(random_seed);
}

bool cut_viewport(int rx, int ry) {
    if (ubo.viewport.x != 0 &&
        (rx < ceil(((ubo.width - ubo.viewport.x) / 2.0)) ||
        (rx > ceil(((ubo.width + ubo.viewport.x) / 2.0))))) return true;
    if (ubo.viewport.y != 0 &&
        (ry < ceil(((ubo.height - ubo.viewport.y) / 2.0)) ||
        (ry > ceil(((ubo.height + ubo.viewport.y) / 2.0))))) return true;
    return false;
}

Ray create_ray(vec2 rg) {
	float r = ubo.width / 2.0;
	float b = ubo.height / 2.0;
	float l = -1.0 * r;
	float t = -1.0 * b;
    float u = l + ((r - l) * (float(rg.x) + 0.5)) / ubo.width;
    float v = b + ((t - b) * (float(rg.y) + 0.5)) / ubo.height;
	float d = (cos(ubo.fov / 2.0) / sin(ubo.fov / 2.0)) * r;
    Ray ray;
    ray.direction = normalize((ubo.u * u) + (ubo.v * v) - (ubo.w * d));
    ray.position = ubo.position;
    return ray;
}

bool triangle_intersect(Ray ray, uint triangle_ind, inout Hit hit) {
    Triangle tri = triangleIn[triangle_ind];
    vec3 e1 = tri.b - tri.a;
    vec3 e2 = tri.c - tri.a;
    vec3 h = cross(ray.direction, e2);
    float a = dot(e1, h);
    if (abs(a) < EPS) return false;
    float f = 1.0 / a;
    vec3 s = ray.position - tri.a;
    float u = f*dot(s, h);
    if (u < 0.0 || u > 1.0) return false;
    vec3 q = cross(s, e1);
    float v = f*dot(ray.direction, q);
    if (v < 0.0 || u + v > 1.0) return false;
    hit.distance = f * dot(e2, q);
    if (hit.distance <= EPS) return false;
    hit.material = tri.material;
    hit.position = ray.position + (ray.direction * hit.distance);
    if (tri.an != vec3(0)) {
        hit.normal = normalize((1.0 - u - v)*tri.an + u*tri.bn + v*tri.cn);
    } else {
        hit.normal = normalize(cross(e1, e2));
    }
    return true;
}

bool aabb_intersect(Ray ray, uint node_ind) {
	vec3 dfrac = 1.0 / ray.direction;
    vec3 mindif = (bvhIn[node_ind].min - ray.position)*dfrac;
    vec3 maxdif = (bvhIn[node_ind].max - ray.position)*dfrac;
	float tmin = max(max(min(mindif.x, maxdif.x), min(mindif.y, maxdif.y)), min(mindif.z, maxdif.z));
	float tmax = min(min(max(mindif.x, maxdif.x), max(mindif.y, maxdif.y)), max(mindif.z, maxdif.z));
    return tmax >= 0 && tmin <= tmax;
}

Hit trace(Ray ray, inout uint hit_id) {
    Hit hit;
    hit.distance = -1.0;
    if (ubo.bvhsize == 0) return hit;
    if (!aabb_intersect(ray, 0)) return hit;
    uint stack[MAX_RECURSIVE_DEPTH];
    int stack_ptr = 0;
    stack[stack_ptr++] = 0;
    while (stack_ptr > 0) {
        NodeBVH node = bvhIn[stack[--stack_ptr]];
        if (stack_ptr >= MAX_RECURSIVE_DEPTH - 1) { stack_failure = true; break; }
        if (node.config == 0) {
            Hit trihit;
            if (triangle_intersect(ray, node.left, trihit)) {
                if (hit.distance == -1.0 || trihit.distance < hit.distance) {
                    hit = trihit;
					hit_id = node.left;
                }
            }
        } else if (node.config == 1) {
            if (aabb_intersect(ray, node.left))
                stack[stack_ptr++] = node.left;
        } else if (node.config == 2) {
            if (aabb_intersect(ray, node.right))
                stack[stack_ptr++] = node.right;
        } else {
            if (aabb_intersect(ray, node.left))
                stack[stack_ptr++] = node.left;
            if (aabb_intersect(ray, node.right))
                stack[stack_ptr++] = node.right;
        }
    }
    return hit;
}

float russian_roulette(vec3 throughput) {
    return clamp(max(max(throughput.x, throughput.y), throughput.z), 0.05, 1.0);
}

vec3 onb(vec3 normal, vec3 local) {
	vec3 w = normal;
	vec3 a = (abs(w.x) > 0.9) ? vec3(0, 1, 0) : vec3(1, 0, 0);
	vec3 v = normalize(cross(w, a));
	vec3 u = normalize(cross(w, v));
	return normalize(local.x*u + local.y*v + local.z*w);
}

vec3 uniform_sample_hemisphere() {
    float r1 = random();
    float r2 = random();
    float sqr2 = sqrt(r2);
    float phi = 2.0 * PI * r1;
    return vec3(cos(phi)*sqr2, sin(phi)*sqr2, sqrt(1.0 - r2));
}

void brdf(in Hit h, in Material material, inout vec3 incoming, inout float pdf, inout vec3 throughput) {
    switch (material.model) {
        case LAMBERTIAN_MODEL:
            incoming = onb(h.normal, uniform_sample_hemisphere());
            pdf = max(0.0, dot(h.normal, incoming)) / PI;
            throughput = material.diffuse / PI;
        default: break;
    }
}

vec3 pathtrace(Ray ray, inout uint hit_id) {
    vec3 throughput = vec3(1.0);
    bool firsthit = true;
    uint hid = -1;
    for (uint i = 0; i < MAX_BOUNCES; i++) {
        Hit h = trace(ray, hid);
        if (h.distance > 0) {
            if (firsthit) {
                firsthit = false;
                hit_id = hid;
            }
            Material material = materialIn[h.material];
            if (material.emission != vec3(0.0)) {
                return material.emission * throughput;
            } else {
                vec3 incoming;
                vec3 color;
                float pdf;
                brdf(h, material, incoming, pdf, color);
                ray.position = h.position + (incoming * EPS);
                ray.direction = incoming;
                throughput *= color * (max(0.0f, dot(incoming, h.normal)) / pdf);
                float p = russian_roulette(throughput);
                if (random() < p) {
                    throughput /= p;
                } else {
                    return vec3(0.0); // TODO: early terminate
                }
            }
        } else {
            return vec3(0.0); // TODO: miss terminate
        }
    }
    return vec3(0.0); // TODO: max bounces terminate
}

void main() {
	// update ray history
	raygenIn[gl_GlobalInvocationID.x].time += ubo.frametime;

	// get ray generator
    RayGenerator rgIn = raygenIn[gl_GlobalInvocationID.x];

	// create ray generator coordinates	
	int rx = int(gl_GlobalInvocationID.x%int(ubo.width));
    int ry = int(gl_GlobalInvocationID.x/int(ubo.width));

	// calculate frame chance
	float chance = 1.0 - pow(1.0 - ubo.frameless, rgIn.time);
    if (ubo.frameless >= 1.0) chance = 1.0;
	float rnum = noise((rx * ry) / (123.456789 + (ubo.seed % 100)));
	bool update_signal = rnum <= chance;
	if (!update_signal) {
        imageStore(hdrImage, ivec2(rx, ry), vec4(0.0));
        return;
    }

	// clear ray history
	raygenIn[gl_GlobalInvocationID.x].time = 0.0;

	// reject any rays outside of the viewport
    if (cut_viewport(rx, ry)) return;

	// calculate ray color
    random_seed = (rx * ry) / (123.4567890123456789 + (ubo.seed % 100));
    uint hit_id = -1;
    vec3 color = pathtrace(create_ray(vec2(rx, ry)), hit_id);
    raygenIn[gl_GlobalInvocationID.x].tid = hit_id;
    
    // failures
    if (stack_failure) color = vec3(1.0, 0.0, 0.0);

    // write to image
    if (ubo.reset != 0) {
	    imageStore(hdrImage, ivec2(rx, ry), vec4(color, 1.0));
    } else {
        vec4 accum = imageLoad(hdrImage, ivec2(rx, ry));
        imageStore(hdrImage, ivec2(rx, ry), vec4(color, 0.0) + accum);
    }
	
	// set mouse hovered id
    if (rx == ubo.mouse_x && ry == ubo.mouse_y) {
		hovered_tid = hit_id;
    }

	// set hovered id to -1 if out of image bounds
	if (ubo.mouse_x > ubo.width || ubo.mouse_y > ubo.height) {
		hovered_tid = -1;
	}
}
