#import Boilerplate

layout(binding = 0) #import MortonSSBODef;
layout(binding = 1) #import IndexSSBODef;
layout(binding = 2) #import MortonSSBOSwapDef;
layout(binding = 3) #import IndexSwapSSBODef;
layout(binding = 4) #import WorkGroupOffsetSSBODef;
layout(binding = 5) #import BucketBaseSSBODef;
layout(push_constant) #import PushConstantDef pc;

void main() {
    uint idx = gl_GlobalInvocationID.x;
    if(idx >= pc.elements) return;
    uint tid = gl_LocalInvocationID.x;
    uint wgID = gl_WorkGroupID.x;
    uint local_count = 0;
    if (pc.bitstart%8 == 0) {
        uint bucket = (mortonIn[idx] >> pc.bitstart) & 0xFu;
        for(uint i = 0; i < tid; i++) {
            uint other_idx = wgID*gl_WorkGroupSize.x + i;
            if(other_idx < pc.elements){
                uint other_bucket = (mortonIn[other_idx] >> pc.bitstart) & 0xFu;
                if(other_bucket == bucket) local_count++;
            }
        }
        uint base = 0;
        for (uint i = 0; i < bucket; i++) base += bucketIn[i];
        uint out_index = base + globalOffset[wgID][bucket] + local_count;
        mortonSwap[out_index] = mortonIn[idx];
        triSwap[out_index] = indexIn[idx];
    } else {
        uint bucket = (mortonSwap[idx] >> pc.bitstart) & 0xFu;
        for(uint i = 0; i < tid; i++) {
            uint other_idx = wgID*gl_WorkGroupSize.x + i;
            if(other_idx < pc.elements){
                uint other_bucket = (mortonSwap[other_idx] >> pc.bitstart) & 0xFu;
                if(other_bucket == bucket) local_count++;
            }
        }
        uint base = 0;
        for (uint i = 0; i < bucket; i++) base += bucketIn[i];
        uint out_index = base + globalOffset[wgID][bucket] + local_count;
        mortonIn[out_index] = mortonSwap[idx];
        indexIn[out_index] = triSwap[idx];
    }
}
