#version 450

layout(binding = 0) uniform UniformBufferObject {
	vec3 look;
	vec3 position;
	vec3 up;
    vec3 u;
    vec3 v;
    vec3 w;
    float fov;
    float width;
    float height;
    uint triangles;
    vec2 viewport;
    uint bvhsize;
	float frametime;
	float frameless;
	uint seed;
	uint shadows;
	uint reflections;
	uint lighting;
    uint raytrace;
    uint sdf;
    uint sdfsize;
    float sdfsmooth;
    uint maxmarches;
    float time;
    uint antialiasing;
    uint lightssize;
    uint grid;
	uint mouse_x;
	uint mouse_y;
    uint samples;
    uint reset;
} ubo;

layout(binding = 1, rgba8) uniform image2D outputImage;

layout(binding = 2, rgba16f) uniform image2D hdrImage;

layout (local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

void main() {
	int rx = int(gl_GlobalInvocationID.x%int(ubo.width));
    int ry = int(gl_GlobalInvocationID.x/int(ubo.width));
	vec3 hdr_color = vec3(imageLoad(hdrImage, ivec2(rx, ry)) / (float(ubo.samples) / 2.0)); // TODO: fix because 2.0 needs to correspond to the cpu target pipeline length
    hdr_color = (hdr_color * ((hdr_color/400) + vec3(1.0)))/(vec3(1.0) + hdr_color); // TODO: bind to ubo defined white point
    hdr_color = pow(hdr_color, vec3(1.0 / 2.2)); // TODO: 2.2 is gamma correction, extend to ubo settings
	imageStore(outputImage, ivec2(rx, ry), vec4(hdr_color, 1.0));
}
