#import Boilerplate

layout(binding = 0) #import UniformBufferObjectDef ubo;
layout(binding = 1, rgba8) #import OutputImageDef;
layout(binding = 2, rgba16f) #import HDRImageDef;

void main() {
	int rx = int(gl_GlobalInvocationID.x%int(ubo.width));
    int ry = int(gl_GlobalInvocationID.x/int(ubo.width));
	vec3 hdr_color = vec3(imageLoad(hdrImage, ivec2(rx, ry)) / (float(ubo.samples) / ubo.swap));
    hdr_color = (hdr_color * ((hdr_color/ubo.whitepoint) + vec3(1.0)))/(vec3(1.0) + hdr_color);
    hdr_color = pow(hdr_color, vec3(1.0 / ubo.gamma)) / ubo.swap;
	imageStore(outputImage, ivec2(rx, ry), vec4(hdr_color, 1.0));
}
