#import Boilerplate
#import Definitions

#import MeshDescriptorDef;
#import VertexSkinDef;

layout(binding = 0) readonly #import VertexSSBODef;
layout(binding = 1) #import TransformedVertexSSBODef;
layout(binding = 2) readonly #import TransformsSSBODef;
layout(binding = 3) readonly #import PoseSSBODef;
layout(binding = 4) readonly #import SkinSSBODef;
layout(push_constant) #import PushConstantDef pc;

uint find_transform(uint i) {
    float pct = float(i) / float(transformsIn[pc.elements - 1].end + 1);
    if (pct >= 1.0) return -1;
    uint ind = uint(pct * float(pc.elements));
    for (int i = 0; i < pc.elements; i++) {
        MeshDescriptor md = transformsIn[ind];
        if (gl_GlobalInvocationID.x >= md.start && gl_GlobalInvocationID.x <= md.end) return ind;
        else if (gl_GlobalInvocationID.x < md.start) ind--;
        else ind++;
    }
    return -1;
}

void animate_vertex(inout vec4 vertex, uint poffset, VertexSkin skin) {
    mat4 skin_mat = mat4(0);
    for (int i = 0; i < MAX_BONE_INFLUENCES; i++)
        skin_mat += skin.weights[i] * poseIn[poffset + skin.indices[i]];
    vertex = skin_mat * vec4(vertex.xyz, 1.0);
}

void main() {
    if (pc.elements == 0) return;
    vec4 vertex = originalVertexIn[gl_GlobalInvocationID.x];
    uint mi = find_transform(gl_GlobalInvocationID.x);
    if (mi == -1) {
        vertexIn[gl_GlobalInvocationID.x] = vertex;
        return;
    }
    MeshDescriptor md = transformsIn[mi];
    if (md.disabled != 0) {
        vertexIn[gl_GlobalInvocationID.x] = vec4(0);
        return;
    }
    if (md.pose != -1)
        animate_vertex(vertex, md.pose, skinIn[(gl_GlobalInvocationID.x - md.start) + md.skinstart]);
    vec3 newpos = (md.transform * vec4(vertex.xyz, 1.0)).xyz;
    vertexIn[gl_GlobalInvocationID.x] = vec4(newpos, originalVertexIn[gl_GlobalInvocationID.x].w);
}
