#ifndef VCONFIG_H
#define VCONFIG_H

#define CPUSWAP_LENGTH 2
#define IMAGE_FORMAT VK_FORMAT_R8G8B8A8_SRGB
#define INVOCATION_GROUP_SIZE 512
#define FRAMELESS_CHANCE 1.0f;

#ifdef PROD_BUILD
    #define ENABLE_VK_VALIDATION_LAYERS FALSE
#else
    #define ENABLE_VK_VALIDATION_LAYERS TRUE
#endif

#endif
