#ifndef VCONFIG_H
#define VCONFIG_H

#include "data/config.h"

#define CPUSWAP_LENGTH 2
#define IMAGE_FORMAT VK_FORMAT_R8G8B8A8_SRGB
#define INVOCATION_GROUP_SIZE 256

void SUPER_DISABLE_VALIDATION_LAYERS();
BOOL VALIDATION_LAYERS_SUPER_ENABLED();

#ifdef PROD_BUILD
    #define ENABLE_VK_VALIDATION_LAYERS FALSE
#else
    #define ENABLE_VK_VALIDATION_LAYERS VALIDATION_LAYERS_SUPER_ENABLED()
#endif

#endif
